### ISSUE TITLE
ValueErrors raised for empty secrets even if stored value is intentionally empty

### ISSUE THREAD

**Issue by MicahJackson** [Astropilot/infisical-python#12]
https://github.com/Astropilot/infisical-python/blob/1cefa5307fc96d97313fd4745c524315b12e823a/infisical/utils/crypto.py#L149

**Comment by Astropilot** [comment]
Hi @MicahJackson ,

Good catch, I didn't think about empty secrets!
The bug is fixed in the version 1.0.1 👍
